NAME = "standard_user"
PASSWORD = "secret_sauce"
FIRST_NAME = "Joe"
LAST_NAME = "Lowson"
POSTAL_CODE = "1234"
NAME_PROBLEM_USER = "problem_user"
NAME_PERFORMANCE_GLITCH_USER = "performance_glitch_user"
WRONG_PASS = "wrong_pass"
FAKE_USER = "fake_user"
EMPTY_NAME = ""
EMPTY_PASSWORD = ""
NAME_SQL_INJ = "' OR '1'='1"
PASSWORD_SQL_INJ = "anything"
NAME_XSS = "<script>alert(1)</script>"
